packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@prisma/engines"
  - esbuild
  - prisma

ignoredBuiltDependencies:
  - "@scarf/scarf"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  esbuild: true
  prisma: true
